name: Deploy Vue App to Debian Server

on:
  push:
    tags:
      - "v*"  # Trigger hanya jika ada push tag version baru (contoh: v1.0.0)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 18.140.85.74 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/id_rsa admin@18.140.85.74 << 'EOF'
          cd /var/www/vue-autodeploy/sample-autodeploy  # Ganti dengan path project Vue di server
          git pull origin main
          npm install
          npm run build
          systemctl restart nginx  # Restart Nginx jika pakai Nginx
          EOF
